//this file handles all inititalization and events related to WebSocket 
var WebSocket = require('ws');  //import ws module 
var WebSocketServer = WebSocket.Server;
var port = 3001;
//websocket server is established and bound to specified port 
var ws = new WebSocketServer({
    port: port
});
var messages = [];

console.log('websockets server started');

/*
- establish callback(event handler callback) for any 'connection' events for your server 
- when client makes connection to ws server, you have access to connection 
via socket object 
*/
ws.on('connection', function(socket) {
    console.log('client connection established');

    messages.forEach(function(msg) {
        socket.send(msg);
    });

/*echo server: repeats any messages sent to it
- register callback for any message events generated by client connection
*/
    //echo functionality 
    socket.on('message', function(data) {
        console.log('message received: '+ data);
        messages.push(data);
        //socket.send(data);
        ws.clients.forEach(function(clientSocket) {
            clientSocket.send(data);
        });
    });
});
